// <auto-generated />
using MAgicVilla_VillaAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace MAgicVilla_VillaAPI.Migrations;

[DbContext(typeof(ApplicationDbContext)), Migration("20250410100114_AddVillaTable")]
internal class AddVillaTableBase
{
    /// <inheritdoc />
    protected  void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "9.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("MAgicVilla_VillaAPI.Models.Villa", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                b.Property<string>("Amenity")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("CreatedDate")
                    .HasColumnType("datetime2");

                b.Property<string>("Details")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("ImageUrl")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasColumnType("nvarchar(max)");

                b.Property<int>("Occupancy")
                    .HasColumnType("int");

                b.Property<double>("Rate")
                    .HasColumnType("float");

                b.Property<int>("Sqft")
                    .HasColumnType("int");

                b.Property<DateTime>("UpdatesdDate")
                    .HasColumnType("datetime2");

                b.HasKey("Id");

                b.ToTable("Villas");
            });
#pragma warning restore 612, 618
    }
}